basic.forever(function () {
    music.playMelody("C5 C E G F A D C5 ", 500)
    music.playMelody("C5 B A G F E D E ", 500)
    music.playMelody("G E C B F C5 D A ", 500)
    music.playMelody("D G E B F C5 A C ", 500)
    music.playMelody("D G E B F C5 A C ", 500)
    basic.showString("Hello!")
    basic.showString("welcome")
    basic.showString("Noah")
})
